version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: citation_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: citation_db
      MYSQL_USER: citation_user
      MYSQL_PASSWORD: citation_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/dataBase/migrations/sql.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./backend
    container_name: citation_backend
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_USER: citation_user
      DB_PASS: citation_password
      DB_NAME: citation_db
      DB_PORT: 3306
      JWT_SECRET: votre_secret_jwt_tres_long_et_complexe_ici_123456789
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    working_dir: /app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: citation_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: citation_user
      PMA_PASSWORD: citation_password
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: 