[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildDirectory = "backend"

[deploy]
startCommand = "cd backend && node app.js"
healthcheckPath = "/api/quotes"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production" 