[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildDirectory = "."

[deploy]
healthcheckPath = "/api/quotes/random"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production"
PORT = "3000"  # Port pour le backend Node.js 