[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildDirectory = "."

[deploy]
startCommand = "node backend/app.js"
healthcheckPath = "/api/quotes"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production" 