[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
buildDirectory = "backend"

[deploy]
startCommand = "node app.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production" 